name: Hello World
on:
  push:
    branches: [ "main" ]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"

  list-job:
    runs-on: ubuntu-latest
    steps:
      - name: list 
        run: ls -la
        
